title: Digitus
description: "Linjeforeningen for Informatikk: digital √∏konomi og ledelse ved Universitetet i Oslo."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

contact_board: "styret@digitusuio.no"
contact_leader: "leder@digitusuio.no"

about: "Digitus er linjeforeningen for studentene p√• <a href='https://www.uio.no/studier/program/informatikk-ledelse/' target='_blank'>Informatikk: Digital √∏konomi og ledelse</a> (Dig√∏k) ved Universitetet i Oslo. Vi arrangerer faglige og sosiale arrangementer for studentene v√•re, og tar vare p√• deres interesser p√• Ifi."
about_image: "/assets/img/styret.jpg"

instagram_limit: 6

partner_url: "https://www.tietoevry.com/"
partner_logo: "assets/img/Tietoevry_logo.svg"
partner_text: "Tietoevry er en av Nordens ledende leverand√∏rer innen digitale tjenester og bygger en smart og b√¶rekraftig fremtid. Vi gleder oss til arrangementer sammen med Tietoevry, og til √• se hvilke muligheter de har for oss Dig√∏kere."
partner_vacancies_header: "Graduate Program"
partner_vacancies: [
 {
    deadline: "9. oktober 2022 ‚è∞",
    title: "Tietoevry ansetter nyutdannede! üéì",
    link: "https://bit.ly/3DWuNs8",
    text: "V√•r samarbeidspartner Tietoevry tilbyr unik mulighet for Dig.√∏k-studenter med oppstart h√∏sten 2023 üë©‚ÄçüíªüöÄ
    Hos Tietoevry kan du hjelpe bedrifter og samfunn med √• n√• deres fulle potensiale ‚Äì samtidig som du n√•r ditt eget.
    <br/><a href='https://www.tietoevry.com/en/campaigns/2022/graduate-program/' target='_blank'>Les mer om graduate programmet her</a>"
  },
]

events_desc: "Vi vil gjerne ha ris, ros og arrangementsforslag. <a href='https://forms.gle/Mttzz249kaA8imkS9' target='_blank'>Send inn ditt her!</a>"
events: "assets/pictures/arrplan.jpg"

press: [
  {
    title: "Elitestudentenes beste r√•d: Slik studerer du for √• f√• toppkarakter",
    subtitle: "e24, 21. oktober 2021",
    link: "https://e24.no/shared/karriere-og-ledelse/i/JxB90b/elitestudentenes-beste-raad-s[‚Ä¶]335030e04eb816f7a9f5176dbbb410e5c8c3a_1635399771_S2plbGwgQmVybnQ=",
  },
  {
    title: "Hvorfor ta en master i informatikk: digital √∏konomi og ledelse?",
    subtitle: "UiO, 22. mars 2021",
    link: "https://www.uio.no/studier/program/informatikk-ledelse-master/studiemiljo/hvorfor-ta-en-master-i-informatikk.html",
  },
  {
    title: "Hvordan er det √• studere digital √∏konomi og ledelse?",
    subtitle: "UiO, 12. mai 2020",
    link: "https://www.uio.no/studier/program/informatikk-ledelse/studiemiljo/digok-fremtidens-arbeidsoppgaver-ahlam.html",
  },
  {
    title: "Her er n√•l√∏yet trangest",
    subtitle: "Dagens N√¶ringsliv, 19. juli 2018",
    link: "https://www.dn.no/utdannelse/samordna-opptak/studieretning/her-er-naloyet-trangest/2-1-381991",
  },
  {
    title: "I fjor fikk Eivinds studie s√• mange s√∏kere at de m√•tte doble kapasiteten.",
    subtitle: "Aftenposten, 18. juli 2018",
    link: "https://www.aftenposten.no/karriere/I-fjor-fikk-Eivinds-studium-sa-mange-sokere-at-de-matte-doble-kapasiteten-Her-er-arets-mest-populare-studier-11872b.html",
  },
  {
    title: "Fremtidens leder",
    subtitle: "UiO.no, 22. juni 2018",
    link: "https://www.uio.no/studier/program/informatikk-ledelse/karriereintervjuer/dig%C3%B8k-julie-eld%C3%B8y.html",
  },
  {
    title: "‚ÄúAlle‚Äù vil til it-studier",
    subtitle: "Dagens N√¶ringsliv, 19. april 2018",
    link: "https://www.dn.no/utdannelse/samordna-opptak/uio/samordna/alle-vil-til-it-studier/2-1-317669",
  },
  {
    title: "Knallhard kamp om studieplassene",
    subtitle: "Dagens N√¶ringsliv, 19. juli 2017",
    link: "https://www.dn.no/utdannelse/samordna-opptak/nils-martin-stolen/julie-eldoy/knallhard-kamp-om-it-studieplassene/2-1-127101",
  },
  {
    title: "Fremtidens ledere har solid digital kompetanse",
    subtitle: "Titan (UiO), 17. mars 2017",
    link: "https://titan.uio.no/node/2233",
  },
]

board_members: [
  {
    name: "Kim Isak Olsen",
    img: "assets/img/leder.jpg",
    role: "Leder",
    mail: "leder@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/kimisak/",
    grade: "5",
  },
  {
    name: "Elias S. Ramsvik",
    img: "assets/img/nestleder.jpg",
    role: "Nestleder",
    mail: "nestleder@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/elias-s-ramsvik-0519431b0/",
    grade: "3",
  },
  {
    name: "Stefan Spanic",
    img: "assets/img/√∏ko.jpg",
    role: "√òkonomiansvarlig",
    mail: "okonomi@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/stefanspanic/",
    grade: "2",
  },
  {
    name: "Synn√∏ve Nordvik Helgesen",
    img: "assets/img/event.jpg",
    role: "Eventansvarlig",
    mail: "event@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/synnovehelgesen/",
    grade: "2",
  },
  {
    name: "Sindre Lianes Nilsen",
    img: "assets/img/bedrift.jpg",
    role: "Bedriftskontakt",
    mail: "bedrift@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/sindre-lianes-nilsen-7708b2207/",
    grade: "4",
  },
  {
    name: "Julie Aamnes",
    img: "assets/img/pr.jpg",
    role: "PR-ansvarlig",
    mail: "pr@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/julie-aamnes-95b90b1b6/",
    grade: "3",
  },
  {
    name: "Nora Alexandra Joakimsen",
    img: "assets/img/senior.jpg",
    role: "Seniormedlem",
    mail: "senior@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/nora-alexandra-joakimsen-631045163/",
    grade: "4",
  },
  {
    name: "Sara Sola",
    img: "assets/img/styremedlem1.jpg",
    role: "Styremedlem",
    mail: "styremedlem1@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/sara-sola-30790b1b6/",
    grade: "3",
  },
  {
    name: "Sivert Karlsen",
    img: "assets/img/styremedlem2.jpg",
    role: "Styremedlem",
    mail: "styremedlem2@digitusuio.no",
    linkedin: "https://www.linkedin.com/in/sivertkarlsen/",
    grade: "4",
  },
]
